- name: Place PHP configuration files in place.
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=644
  become: yes
  with_items:
    - { src: xdebug.ini.j2, dest: "{{ etc_php_path }}/mods-available/xdebug.ini" }

- name: Activate PHP configuration files
  command: "{{php_phpenmod}} {{ item }}"
  with_items:
    - xdebug
  become: yes
