- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ php_version_installed }}.yml"
    - "{{ ansible_distribution }}-{{ php_version_installed | int }}.x.yml"
    - "{{ ansible_distribution }}.yml"
  when: "php_version_installed is defined"

- name: install PHP redis extension
  apt: pkg={{ php_redis_package }} state=latest
  become: yes
  notify:
    - restart webserver

