- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-{{ php_version_installed }}.yml"
   - "{{ ansible_distribution }}-{{ php_version_installed | int }}.x.yml"
   - "{{ ansible_distribution }}.yml"
   - "default.yml"

- name: install PHP {{ php_version_installed }} memcached extension
  apt: pkg={{ php_memcached_package }} state=latest
  become: yes
  notify:
    - restart webserver
